"""
NexusAI AI - Education Response Formatter

Formats Education AI responses before sending them
to the frontend.

The formatter is responsible only for metadata.
It NEVER modifies the generated Markdown content.
"""

from datetime import datetime


MODE_TITLES = {

    "learn": "📘 Learn Mode",

    "notes": "📄 Study Notes",

    "exam": "📝 Exam Mode",

    "coding": "💻 Coding Tutor",

    "quiz": "🎯 Quiz Mode",

    "interview": "🎤 Interview Preparation",

    "roadmap": "🗺 Learning Roadmap",

    "revision": "⚡ Quick Revision",

}


def format_response(
    mode: str,
    content: str,
) -> dict:
    """
    Format Education AI response.

    Parameters
    ----------
    mode : str
        Detected education mode.

    content : str
        Markdown generated by the LLM.

    Returns
    -------
    dict
        Standardized response object.
    """

    if content is None:

        content = (
            "# ❌ Empty Response\n\n"
            "The AI did not generate any content."
        )

    content = str(
        content
    ).strip()

    if not content:

        content = (
            "# ❌ Empty Response\n\n"
            "The AI returned an empty response."
        )

    return {

        "success": True,

        "agent": "education",

        "mode": mode,

        "title": MODE_TITLES.get(
            mode,
            "📚 Education AI",
        ),

        # ReactMarkdown renders this field.
        "response": content,

        # Helpful metadata
        "content_type": "markdown",

        "timestamp": datetime.utcnow().isoformat(),

    }