import os
import logging
from langgraph.graph import StateGraph, END
from langsmith import traceable
from langsmith.run_helpers import get_current_run_tree

from agents.router import route_after_testing
from agents.state import AgentState
from agents.planner import planner_agent
from agents.coder import coder_agent
from agents.tester import tester_agent
from agents.debugger import debugger_agent
from agents.deployer import deployer_agent
from db.postgres_logger import log_agent_run

logger = logging.getLogger(__name__)

# Wrapped Traced and PostgreSQL Logged Agent Nodes
@traceable(run_type="chain", name="planner_agent")
def traced_planner_agent(state):
    with log_agent_run("planner", state):
        try:
            if os.environ.get("LANGCHAIN_TRACING_V2") == "true":
                rt = get_current_run_tree()
                if rt:
                    rt.add_tags(["agent_name", "planner"])
                    rt.add_metadata({
                        "agent_name": "planner",
                        "task_id": state.get("execution_id"),
                        "project_id": state.get("project_id"),
                        "user_id": state.get("user_id")
                    })
        except Exception as e:
            logger.warning(f"Failed to add LangSmith run tree metadata: {e}")
            
        res = planner_agent(state)
        
        # Link project_id to task in PostgreSQL once generated by planner
        project_id = res.get("project_id")
        task_id = res.get("execution_id")
        if task_id and project_id:
            try:
                from db.postgres import update_task_pg_sync
                update_task_pg_sync(task_id, project_id=project_id)
            except Exception as e:
                logger.error(f"Failed to associate project_id {project_id} to task {task_id}: {e}")
                
        return res

@traceable(run_type="chain", name="coder_agent")
def traced_coder_agent(state):
    with log_agent_run("coder", state):
        try:
            if os.environ.get("LANGCHAIN_TRACING_V2") == "true":
                rt = get_current_run_tree()
                if rt:
                    rt.add_tags(["agent_name", "coder"])
                    rt.add_metadata({
                        "agent_name": "coder",
                        "task_id": state.get("execution_id"),
                        "project_id": state.get("project_id"),
                        "user_id": state.get("user_id")
                    })
        except Exception as e:
            logger.warning(f"Failed to add LangSmith run tree metadata: {e}")
        return coder_agent(state)

@traceable(run_type="chain", name="tester_agent")
def traced_tester_agent(state):
    with log_agent_run("tester", state):
        try:
            if os.environ.get("LANGCHAIN_TRACING_V2") == "true":
                rt = get_current_run_tree()
                if rt:
                    rt.add_tags(["agent_name", "tester"])
                    rt.add_metadata({
                        "agent_name": "tester",
                        "task_id": state.get("execution_id"),
                        "project_id": state.get("project_id"),
                        "user_id": state.get("user_id")
                    })
        except Exception as e:
            logger.warning(f"Failed to add LangSmith run tree metadata: {e}")
            
        res = tester_agent(state)
        
        # Log pass/fail feedback hook to LangSmith parent graph run
        try:
            if os.environ.get("LANGCHAIN_TRACING_V2") == "true":
                rt = get_current_run_tree()
                if rt and rt.parent_run:
                    from langsmith import Client
                    client = Client()
                    passed = res.get("test_results", {}).get("status") == "PASS"
                    client.create_feedback(
                        run_id=rt.parent_run.id,
                        key="tester_pass",
                        score=1.0 if passed else 0.0,
                        comment=f"Tester node completed with status: {res.get('test_results', {}).get('status', 'FAIL')}"
                    )
        except Exception as e:
            logger.warning(f"Failed to send feedback score to LangSmith: {e}")
            
        return res

@traceable(run_type="chain", name="debugger_agent")
def traced_debugger_agent(state):
    with log_agent_run("debugger", state):
        try:
            if os.environ.get("LANGCHAIN_TRACING_V2") == "true":
                rt = get_current_run_tree()
                if rt:
                    rt.add_tags(["agent_name", "debugger"])
                    rt.add_metadata({
                        "agent_name": "debugger",
                        "task_id": state.get("execution_id"),
                        "project_id": state.get("project_id"),
                        "user_id": state.get("user_id")
                    })
        except Exception as e:
            logger.warning(f"Failed to add LangSmith run tree metadata: {e}")
        return debugger_agent(state)

@traceable(run_type="chain", name="deployer_agent")
def traced_deployer_agent(state):
    with log_agent_run("deployer", state):
        try:
            if os.environ.get("LANGCHAIN_TRACING_V2") == "true":
                rt = get_current_run_tree()
                if rt:
                    rt.add_tags(["agent_name", "deployer"])
                    rt.add_metadata({
                        "agent_name": "deployer",
                        "task_id": state.get("execution_id"),
                        "project_id": state.get("project_id"),
                        "user_id": state.get("user_id")
                    })
        except Exception as e:
            logger.warning(f"Failed to add LangSmith run tree metadata: {e}")
            
        res = deployer_agent(state)
        
        # When Deployer finishes, the multi-agent task is completed!
        task_id = res.get("execution_id")
        if task_id:
            try:
                from db.postgres import update_task_pg_sync
                from datetime import datetime
                update_task_pg_sync(task_id, status="completed", completed_at=datetime.utcnow())
            except Exception as e:
                logger.error(f"Failed to mark task {task_id} as completed in PG: {e}")
                
        return res

# Workflow Setup
workflow = StateGraph(AgentState)

# Traced Nodes
workflow.add_node("planner", traced_planner_agent)
workflow.add_node("coder", traced_coder_agent)
workflow.add_node("tester", traced_tester_agent)
workflow.add_node("debugger", traced_debugger_agent)
workflow.add_node("deployer", traced_deployer_agent)

# Entry Point
workflow.set_entry_point("planner")

# Graph Connections
workflow.add_edge("planner", "coder")
workflow.add_edge("coder", "tester")

# Conditional testing edge
workflow.add_conditional_edges(
    "tester",
    route_after_testing,
    {
        "debugger": "debugger",
        "end": "deployer"
    }
)

# Fix loop
workflow.add_edge("debugger", "tester")
workflow.add_edge("deployer", END)

graph = workflow.compile()